require 'rake/testtask'
Rake::TestTask.new do |t|
    t.libs << "test"
    t.test_files = FileList['test/test*.rb']
    t.verbose = true
  end

desc "Crear Archivo tar.gz"
task :dist do
	sh "tar -cvf P_HTML.tar *"
	sh "gzip P_HTML.tar"
end

desc "Crear Archivo .zip"
task :zip do
	sh "zip -r P_HTML.zip *"
end

desc "Borrar Ficheros Temporales"
task :clean do
	system 'find . -type f -name "*.tmp" -exec rm -f {} \;'
end
